
before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev jq
  - cat mona | /bin/bash
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - gem install bundler --no-document
rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop

rubocoopl:
  script:
    - bundle exec rubocoopl
